name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Find-NICK/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: Find-NICK
          filename: src/metric.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Etc/GMT-8
          plugin_activity: yes
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_visibility: push, issue, pr, ref/create, ref/delete, release, wiki, fork, star, public, member
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_traffic: yes
