name: stars
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  followers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Find-NICK/metrics@master
        with:
          filename: src/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 5
