name: WakaTime
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.wakatime.svg
  token: NOT_NEEDED
  base: ""
  plugin_wakatime: yes
  plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
  plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
